@startuml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста для монолитного приложения "Тёплый дом"

Person(user, "Клиент", "Владелец дома, использует систему для управления отоплением.")
Person(инженер, "Инженер по подключению", "Специалист, подключающий оборудование к системе.")
System_Boundary(Монолит, "Монолитное приложение 'Тёплый дом'") {
    System(УправлениеОборудованием, "Управление оборудованием", "Обрабатывает команды пользователя для управления отоплением дома, светом и т.д..")
    System(МониторингОборудования, "Мониторинг оборудования", "Получает данные о температуре, о состоянии выключателей и т.д.")
    System(СервисПодключения, "Сервис подключения", "Выполняет подключение оборудования.")
}

System_Ext(Датчики, "Датчики температуры", "Передают данные о текущей температуре в доме.")
System_Ext(Реле, "Реле отопления", "Управляют включением/выключением отопления в доме.")
System_Ext(Оборудование, "Оборудование умного дома", "Управляют включением/выключением света, управления камерами, воротами и т.д..")

Rel(user, УправлениеОборудованием, "Отправляет команды на управление отоплением, светом, воротами")
Rel(user, МониторингОборудования, "Просматривает данные о текущей температуре, состоянии переключателей")
Rel(УправлениеОборудованием, Реле, "Отправляет команды для включения/выключения отопления, света, открытия/закрытия ворот")
Rel(МониторингОборудования, Датчики, "Получает данные о температуре, состоянии выключателей")
Rel(инженер, СервисПодключения, "Выполняет подключение оборудования")
Rel(СервисПодключения, МониторингОборудования, "Регистрирует датчики в системе")
Rel(СервисПодключения, УправлениеОборудованием, "Регистрирует оборудование в системе")

@enduml